/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#343944",
        "surface-container-lowest": "#090e17",
        "surface-container-high": "#252a34",
        "border-glass-active": "rgba(16, 185, 129, 0.35)",
        "surface-container-low": "#171c25",
        "tertiary-container": "#71a1ff",
        "telemetry-cyan": "#06b6d4",
        "on-secondary-container": "#00424e",
        "outline-variant": "#3c4a42",
        "surface-tint": "#4edea3",
        "tertiary": "#adc6ff",
        "outline": "#86948a",
        "on-tertiary-fixed": "#001a42",
        "inverse-surface": "#dee2f0",
        "secondary-fixed-dim": "#4cd7f6",
        "on-secondary-fixed-variant": "#004e5c",
        "text-muted": "#94a3b8",
        "on-error-container": "#ffdad6",
        "surface-slate-base": "#0f172a",
        "surface-slate-elevated": "#1e293b",
        "secondary-fixed": "#acedff",
        "secondary-container": "#03b5d3",
        "border-glass": "rgba(255, 255, 255, 0.08)",
        "inverse-primary": "#006c49",
        "on-surface": "#dee2f0",
        "surface-container-highest": "#30353f",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#4edea3",
        "surface-variant": "#30353f",
        "on-primary-container": "#00422b",
        "surface-container": "#1b2029",
        "on-error": "#690005",
        "on-secondary-fixed": "#001f26",
        "on-secondary": "#003640",
        "on-surface-variant": "#bbcabf",
        "surface": "#0f131d",
        "surface-dim": "#0f131d",
        "primary-fixed": "#6ffbbe",
        "primary": "#4edea3",
        "on-tertiary-container": "#00367a",
        "telemetry-emerald": "#10b981",
        "tertiary-fixed-dim": "#adc6ff",
        "surface-obsidian": "#0a0f18",
        "on-primary": "#003824",
        "primary-container": "#10b981",
        "on-tertiary": "#002e6a",
        "tertiary-fixed": "#d8e2ff",
        "live-radar-ping": "#ef4444",
        "on-primary-fixed": "#002113",
        "status-warning": "#f59e0b",
        "background": "#0f131d",
        "on-primary-fixed-variant": "#005236",
        "inverse-on-surface": "#2c303b",
        "error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004395",
        "secondary": "#4cd7f6",
        "text-primary": "#f8fafc",
        "on-background": "#dee2f0"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline-xl": ["Plus Jakarta Sans"],
        "metric-kpi": ["Plus Jakarta Sans"],
        "code-tabular": ["JetBrains Mono"],
        "display-hero": ["Plus Jakarta Sans"],
        "body-sm": ["Inter"],
        "eyebrow-badge": ["JetBrains Mono"],
        "body-md": ["Inter"],
        "display-hero-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Inter"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"]
      }
    }
  },
  plugins: [],
}
